### PR TITLE
Put the alter foreign key and index at the end of DDLs

### PR DESCRIPTION
**Pull request by hokaccha**
fix https://github.com/sqldef/sqldef/issues/405

@k0kubun The impact is significant, so I would appreciate your review.

### CODE REVIEW

**Review by k0kubun — APPROVED** [review]
makes sense to me.

**Comment by hokaccha** [comment]
thanks!

**Comment by yuku** [comment]
Notes for future developers. 

Using inline foreign key with independent unique constraint no longer works as expected:

```sql
CREATE TABLE dests (
  foo INT
);
ALTER TABLE dests ADD CONSTRAINT dests_unique UNIQUE (foo);

CREATE TABLE sources (
  foo INT REFERENCES dests (foo)
);
-- (output) there is no unique constraint matching given keys for referenced table "dests"
```

To address the issue, inline the unique constraint:

```sql
CREATE TABLE dests (
  foo INT,
  CONSTRAINT dests_unique UNIQUE (foo)
);

CREATE TABLE sources (
  foo INT REFERENCES dests (foo)
);
```

**Comment by hokaccha** [comment]
@yuku Thank you. That's right. Or, you could do it like this.

```sql
CREATE TABLE dests (
  foo INT
);
ALTER TABLE dests ADD CONSTRAINT dests_unique UNIQUE (foo);

CREATE TABLE sources (
  foo INT
);
ALTER TABLE sources ADD CONSTRAINT sources_foo_fkey FOREIGN KEY (foo) REFERENCES dests (foo);
```

Either way, it would be better to standardize whether you define it inline or with an ALTER statement.

**Pull request merged**
